/** Types mirroring `backend/models/*.py` Pydantic schemas.
 *  Kept in sync by hand until Prompt 10 wires openapi-typescript. */

export type ProjectStatus =
  | "draft"
  | "configured"
  | "ready"
  | "running"
  | "completed"
  | "errored";

export interface ProjectSummary {
  slug: string;
  display_name: string;
  description: string;
  status: ProjectStatus;
  created_at: string;
  env_id: string | null;
  n_iterations_completed: number;
  // M6: populated when the project references an adapter no longer in
  // ADAPTER_REGISTRY. UI shows a banner hinting at "fork to upgrade".
  migration_warning?: string | null;
  // §Ship 22b (re-skin, Finding A): additive card enrichment from
  // GET /projects. Config fields filled by ProjectStore.list(); metric
  // fields filled by the route from the latest sculpt_run.
  adapter_class?: string | null;
  library_slug?: string | null;
  reference_robot?: string | null;
  num_envs?: number | null;
  device?: string | null;
  primary_metric?: number | null;
  primary_metric_history?: Array<number | null>;
}

export interface ProjectDetail extends ProjectSummary {
  project_dir: string;
  adapter_class: string;
  adapter_config: Record<string, unknown>;
  ready_to_train?: boolean;
  library_slug?: string | null;
  reference_robot?: string | null;
  adapter_unavailable?: boolean;
}

export interface HealthResponse {
  status: "ok" | "degraded";
  sculptor_ok: boolean;
  sculptor_error: string | null;
  projects_root: string;
}

export interface CreateProjectPayload {
  name: string; // maps to display_name server-side
  description?: string;
  adapter?: string;
  iteration_budget?: number;
  behavior_goal?: string;
  // M3 / M4 additions. Backend derives adapter + task_id from
  // library_slug when present; explicit num_envs / gpu_device override
  // the library entry's defaults.
  library_slug?: string;
  task_id?: string;
  num_envs?: number;
  gpu_device?: string;
}

export type RobotKind = "library" | "mjcf" | "urdf" | "none";

export interface RobotStateResponse {
  kind: RobotKind;
  library_name: string | null;
  env_id: string | null;
  model_file: string | null;
  original_filename: string | null;
  size_bytes: number | null;
  uploaded_at: string | null;
  mesh_paths: string[];
}

export type LibraryRobotName =
  | "hopper"
  | "half_cheetah"
  | "ant"
  | "humanoid"
  | "walker2d";

export type CameraAngle = "iso" | "front" | "side" | "top";
export const CAMERA_ANGLES: readonly CameraAngle[] = [
  "iso",
  "front",
  "side",
  "top",
] as const;

/** Wire-format + thumbnail path + display label for each library
 *  robot. Thumbnail lives under frontend/public/robots/ and is
 *  regenerated by scripts/generate_library_thumbnails.py. */
export interface LibraryRobotEntry {
  name: LibraryRobotName;
  displayName: string;
  envId: string;
  thumbnail: string;
  blurb: string;
}

export const LIBRARY_ROBOTS: readonly LibraryRobotEntry[] = [
  {
    name: "hopper",
    displayName: "Hopper",
    envId: "Hopper-v4",
    thumbnail: "/robots/hopper.png",
    blurb: "2D single-leg hopper — canonical locomotion testbed.",
  },
  {
    name: "half_cheetah",
    displayName: "Half-Cheetah",
    envId: "HalfCheetah-v4",
    thumbnail: "/robots/half_cheetah.png",
    blurb: "Planar bipedal runner with a low-slung torso.",
  },
  {
    name: "walker2d",
    displayName: "Walker2D",
    envId: "Walker2d-v4",
    thumbnail: "/robots/walker2d.png",
    blurb: "2D bipedal walker — upright gait, fall-prone without shaping.",
  },
  {
    name: "ant",
    displayName: "Ant",
    envId: "Ant-v4",
    thumbnail: "/robots/ant.png",
    blurb: "Quadruped ant body — omnidirectional locomotion.",
  },
  {
    name: "humanoid",
    displayName: "Humanoid",
    envId: "Humanoid-v4",
    thumbnail: "/robots/humanoid.png",
    blurb: "Full-body humanoid — high-DOF, reward-shaping hard mode.",
  },
] as const;

export interface ProblemDetail {
  type: string;
  title: string;
  status: number;
  detail: string | null;
  instance?: string | null;
  [extra: string]: unknown;
}

// ── Rewards ─────────────────────────────────────────────────────────
export type RewardAuthor = "sculptor" | "human" | "unknown";

export interface RewardRef {
  arxiv_id: string;
  citation: string;
}

export interface RewardComposition {
  type: string;
  reference_clip_id: string | null;
  reference_target_sha256: string | null;
  tracking_weight: number;
  residual_max: number;
  phase_mode?: "loop" | "hold" | string;
  phase_duration_s?: number;
  root_height_frame?: "episode_relative" | string;
}

export interface RewardSpec {
  version: string;
  parent_hash: string;
  author: string;
  description: string;
  hyperparameters: Record<string, number>;
  references: RewardRef[];
  composition?: RewardComposition | null;
  /** Map of `hparam_name → citation-or-justification` — the KG-grounding
   *  mandate from 2026-04-22. Empty for pre-mandate rewards.
   *  SpecPanel renders this alongside hyperparameters so Sam can audit
   *  which arxiv_id / physics principle justifies each numeric choice. */
  grounding: Record<string, string>;
}

export interface ComponentProbe {
  ok: boolean;
  components: Record<string, number> | null;
  total: number | null;
  error: string | null;
}

export interface RewardVersionSummary {
  version: number;
  file_name: string;
  author: RewardAuthor;
  parent_hash: string;
  parent_version: number | null;
  description: string;
  iter_introduced: number | null;
  n_references: number;
  primary_metric: number | null;
  metric_delta: number | null;
  created_at: string;
}

export interface RewardVersionDetail extends RewardVersionSummary {
  source: string;
  spec: RewardSpec;
  components_probe: ComponentProbe;
}

export interface ManualEditPayload {
  source: string;
  expected_parent_version: number;
  note?: string;
}

// ── KG ──────────────────────────────────────────────────────────────
export interface PaperSummary {
  id: string;
  arxiv_id: string;
  title: string;
  authors: string[];
  year: number | null;
  extracted: boolean;
  has_pdf: boolean;
}

export type KGEntityKind =
  | "Technique"
  | "FailureMode"
  | "RewardComponent"
  | "Environment";

export interface KGEntitySummary {
  id: string;
  kind: KGEntityKind;
  name: string;
  description: string;
}

export interface PaperEntities {
  techniques: KGEntitySummary[];
  failure_modes: KGEntitySummary[];
  reward_components: KGEntitySummary[];
  environments: KGEntitySummary[];
}

export interface PaperDetail extends PaperSummary {
  abstract: string;
  conclusion_text: string;
  pdf_available: boolean;
  ingested_at: string | null;
  entities: PaperEntities;
}

export interface TechniqueSummary {
  id: string;
  name: string;
  description: string;
  tags: string[];
  n_addresses: number;
  introduced_by: string[];
}

export interface PendingSeed {
  arxiv_id: string;
  title?: string;
  rationale?: string;
}

export interface PendingSeedsResponse {
  pending: PendingSeed[];
  ingested_count: number;
}

export interface KGStats {
  papers: number;
  techniques: number;
  failure_modes: number;
  reward_components: number;
  environments: number;
  results: number;
  run_cases: number;
  edges: number;
  embeddings: number;
}

export interface AddSeedsPayload {
  seeds: Array<{ arxiv_id: string; title?: string; rationale?: string }>;
  auto_extract?: boolean;
}

// ── Jobs ────────────────────────────────────────────────────────────
export type JobKind =
  | "kg_ingest"
  | "kg_extract"
  | "kg_ingest_extract"
  | "kg_research"
  | "kg_viz_render"
  | "sculpt_run";

export type JobStatus =
  | "queued"
  | "running"
  | "completed"
  | "errored"
  | "stopped";

export const JOB_TERMINAL_STATES: readonly JobStatus[] = [
  "completed",
  "errored",
  "stopped",
] as const;

export interface JobSummary {
  job_id: string;
  kind: JobKind;
  project_slug: string | null;
  status: JobStatus;
  progress: number | null;
  message: string | null;
  started_at: string | null;
  ended_at: string | null;
  error: string | null;
}

export interface JobDetail extends JobSummary {
  params: Record<string, unknown>;
  result: Record<string, unknown> | null;
}

// ── Runs ────────────────────────────────────────────────────────────
export interface RunParamsPayload {
  behavior_goal: string;
  iterations: number;
  no_kg?: boolean;
  dry_run?: boolean;
  /** Explicit research authorization for a live run with no objective
   * fitness. False/omitted is fail-closed; dry runs do not require it. */
  acknowledge_blind_fitness?: boolean;
  // M7 Phase 4 — GPU-appropriate overrides. All optional; null means
  // "use the project's config.toml default".
  training_iterations?: number | null;
  num_envs_override?: number | null;
  device_override?: string | null;
  expand_kg?: boolean;
  // Ship-7 — rollout video + RL knobs. All optional; null means runner
  // default (real-time 500-step video, 6 episodes, seed from config).
  max_episode_steps?: number | null;
  playback_speed?: number | null;
  render_every?: number | null;
  rollout_fps?: number | null;
  // Rollout video resolution; null = runner default (1280×720). Render
  // cost is resolution-independent, so high-res is the sane default.
  render_width?: number | null;
  render_height?: number | null;
  render_env_index?: number | null;
  rollout_episodes?: number | null;
  seed?: number | null;
  auto_adjust_physics?: boolean | null;
  // Legacy compatibility no-ops; metric-plateau auto-kill is disabled.
  early_stop_enabled?: boolean | null;
  early_stop_patience?: number | null;
  // §Ship 34/35 — objective fitness-in-the-loop. A built-in spec name
  // (including capability-driven object_lift_hold) or a generated
  // metric id ("gen:<id>"); null = the blind loop. §Ship 42: the sentinel
  // "generate-at-launch" defers generation to the run's first phase (see
  // run_manager LAUNCH_GEN_SENTINEL).
  fitness_metric?: string | null;
  // observe = compute + display only (no influence); steer = drives the loop.
  fitness_mode?: "observe" | "steer";
  // §best-of-N: candidates to sample for a generate-at-launch metric (1 =
  // single-shot). Only used when fitness_metric === "generate-at-launch".
  metric_n_candidates?: number;
  // §Ship 48: patience for the fitness-plateau early stop (the LIVE early
  // stop on a steered run; the early_stop_* fields above are a no-op for it).
  // null → sculpt default (2). The UI sends 4 for hard exploratory skills.
  fitness_patience?: number | null;
  // §Ship 39 (H1): interactive start mode. "manual" pauses for human feedback
  // at each iteration boundary (the UI default); "auto" runs straight through.
  start_mode?: "manual" | "auto";
  // Explicit recovery path: restore reward + env inputs from the last promoted
  // atomic world tuple before the resumed sculpt process starts.
  resume_exact_tuple?: boolean;
  // Explicit policy-only recovery. The backend resolves this iteration to a
  // non-empty checkpoint inside this project's runs directory.
  warm_start_iteration?: number | null;
  // A reusable, content-addressed starting skill imported through the
  // researcher-facing bundle flow. `initialization_mode` is deliberately
  // explicit: loading an actor is not the same experiment as also loading a
  // critic, and neither is a full optimizer/iteration resume.
  starting_skill_id?: string | null;
  /** Immutable manifest pin from the import/list receipt. Required whenever a
   * starting_skill_id is selected; the server rechecks it at route and worker
   * boundaries so a stale picker cannot launch different bytes. */
  expected_starting_skill_manifest_digest?: string | null;
  initialization_mode?: StartingSkillInitializationMode | null;
  // Optional pre-existing motion. The exact robot namespace is paired with
  // the clip id so the backend never resolves from a fallback embodiment.
  reference_clip_id?: string | null;
  reference_robot?: string | null;
}

/** §Ship 39 (H1): the interactive control sidecar state (PATCH response). */
export interface RunControlState {
  mode: string;
  resume_token: number;
  feedback?: string | null;
  stop: boolean;
}

/** §Ship 34: spec metrics selectable as in-loop objective fitness.
 *  Mirrors sculptor.eval.spec_metrics._SPEC_FNS / the backend Literal. */
export type SpecMetricName =
  | "cartpole_balance"
  | "g1_floss"
  | "g1_jump"
  | "g1_kick"
  | "go1_trot"
  | "object_lift_hold";

/** §Ship 35: an auto-generated objective metric (per project), referenced
 *  in a run as fitness_metric = "gen:<id>". Observe-only until calibrated. */
export interface MetricSummary {
  id: string;
  behavior_goal?: string | null;
  accepted: boolean;
  validation_passed: boolean;
  calibrated: boolean;
  review?: { approved?: boolean; concerns?: string[]; summary?: string } | null;
  gates?: Record<string, boolean> | null;
  reasons?: string[] | null;
  archetype_scores?: Record<string, number> | null;
  validator_basis?: string | null;
  abstract_objective_program?: string[] | null;
  channel_catalog_hash?: string | null;
  calibration?: { ok?: boolean; spearman?: number; builtin?: string } | null;
  // §best-of-N: how many candidates were sampled + which one won (with its
  // offline discrimination). null/1 for the single-shot path.
  n_candidates?: number | null;
  selected_candidate?: number | null;
  candidates?: { candidate: number; ok: boolean; discrimination?: number;
                 reasons?: string[] }[] | null;
  source?: string | null;
  recorded_at?: string | null;
}

/** §Ship 40: live progress while a metric is being generated (polled). */
export interface MetricGenProgress {
  active: boolean;
  stage?: string;
  message?: string;
  attempt?: number;
  max?: number;
}

export const SPEC_METRIC_NAMES: SpecMetricName[] = [
  "cartpole_balance",
  "g1_floss",
  "g1_jump",
  "g1_kick",
  "go1_trot",
  "object_lift_hold",
];

// Extend RunSummary / RunDetail with the new Phase-6 classification
// field. Existing callers that spread `...run` keep working.
export interface RunErrorClassificationFields {
  error_classification?: ErrorClassification | null;
}

export interface RealismAuditPayload {
  verdict: "ok" | "mild" | "severe" | "unknown" | string;
  torque_saturation_frac?: number | null;
  any_joint_saturation_max?: number | null;
  joint_vel_p99_max?: number | null;
  joint_vel_multiplier_vs_nominal?: number | null;
  joint_limit_violation_frac?: number | null;
  top_joints_saturation?: Array<{ name: string; value: number }>;
  top_joints_vel?: Array<{ name: string; value: number }>;
  top_joints_limit_violation?: Array<{ name: string; value: number }>;
  n_actuators?: number;
  n_joints?: number;
  n_steps?: number;
  reason?: string;
}

export interface PhysicsEditSuggestionPayload {
  prompt: string;
  verdict?: string | null;
  top_joints_saturation?: Array<{ name: string; value: number }>;
  // §Ship-8c: sculpt-side auto-apply progress. UI disables the
  // "apply physics fix" chip while this is "in_progress" so a user
  // click can't race against the sculpt loop's own apply.
  auto_apply_state?:
    | "pending"
    | "in_progress"
    | "applied"
    | "rejected"
    | "errored"
    | "skipped";
  auto_apply_summary?: string;
  auto_apply_reason?: string;
}

/** §Ship 48: edits the diagnoser wanted but couldn't ground because the
 *  adapter doesn't expose the needed field (requires_env_extension).
 *  Informational only — an env extension is a code change, never
 *  auto-applied. */
export interface EnvExtensionSuggestionPayload {
  terms: string[];
  rationales?: string[];
}

export interface IterEventSummary {
  iter_index: number;
  status: "running" | "completed" | "errored" | "stopped";
  started_at: string | null;
  completed_at: string | null;
  reward_version_before: number | null;
  reward_version_after: number | null;
  primary_metric: number | null;
  metric_delta: number | null;
  failure_modes: string[];
  edit_count: number | null;
  paper_refs: string[];
  rollout_ready: boolean;
  diagnosed: boolean;
  // §7.3: post-rollout physics realism audit. `null` when
  // `realism_audit.json` hasn't landed on disk yet (iter still running,
  // or pre-§7.3 iter). Verdict + metric fields match
  // `sculptor.adapters.realism.audit_rollout()`.
  realism_audit: RealismAuditPayload | null;
  // §7.4: ready-to-apply MJCF-edit prompt when audit verdict is
  // "severe" AND project config has `auto_adjust_physics = true`. UI
  // surfaces as a chip that opens the Physics tab with prompt pre-filled.
  physics_edit_suggestion: PhysicsEditSuggestionPayload | null;
  // §Ship 48: edits deferred for requires_env_extension this iter (the
  // diagnoser wants a field the adapter doesn't expose). null when none.
  env_extension_suggestion?: EnvExtensionSuggestionPayload | null;
  // §env generalization: the diagnoser's env-curriculum change applied
  // at this iter's boundary (takes effect NEXT iter's training). null
  // until an iter proposes env edits.
  env_spec_update?: {
    new_version: string | null;
    applied: string[];
    rejected: Array<{ parameter: string; reason: string }>;
  } | null;
  // Reward edits the pre-flight grounding check threw out, verbatim. The
  // count alone reads as "the diagnoser had nothing useful"; the reasons
  // say whether the edit was wrong or the checker couldn't see the term
  // it named. Four iterations of the platform-ascent campaign were lost
  // to that difference. null until an iter rejects something.
  edits_rejected?: { count: number; reasons: string[] } | null;
  // Populated by `iter_progress` events emitted from inside the mjlab
  // training subprocess. Lets the Timeline panel render a live progress
  // bar for the running iter instead of a silent "running" spinner.
  rl_iter?: number;
  rl_total?: number;
  pct?: number;
  elapsed_s?: number;
  eta_s?: number | null;
  // §Ship 34: objective fitness-in-the-loop. `fitness` is this iter's
  // ground-truth spec score; `best_fitness` is the best so far (the
  // version best-by-fitness selection keeps). Both undefined for blind
  // runs (no --fitness-metric).
  fitness?: number | null;
  best_fitness?: number | null;
  // §Convergence loop 1: dense sub-success progress (metric progress_score,
  // 0-1) — ranks iterations below the completion gate. Undefined when the
  // metric doesn't emit it.
  progress?: number | null;
}

export interface RunSummary {
  run_id: string;
  project_slug: string;
  status: JobStatus;
  behavior_goal: string;
  iterations_requested: number;
  iterations_completed: number;
  current_iter_index: number | null;
  // §Ship 35: per-iter objective fitness (parallel to primary_metric_history).
  // Empty/all-null for blind runs. When present, the UI foregrounds this as
  // the primary metric and demotes the reward metric to secondary.
  fitness_history?: Array<number | null>;
  primary_metric_history: Array<number | null>;
  started_at: string | null;
  ended_at: string | null;
  error: string | null;
  error_classification?: ErrorClassification | null;
  // §Ship 21: distinguish standalone sculpt_run rows from per-stage
  // mission_stage_run rows. The Runs sidebar groups stage runs under
  // their parent mission. Backend defaults to "sculpt_run" for
  // backward compatibility, so undefined === "sculpt_run".
  kind?: "sculpt_run" | "mission_stage_run";
  parent_id?: string | null;
  mission_slug?: string | null;
  stage_name?: string | null;
  stage_index?: number | null;
  // §Ship 39 (H1): current interactive mode ("manual" | "auto"); null for
  // older / non-interactive runs. Restores the Auto/Manual toggle on reconnect.
  mode?: string | null;
}

export interface RunDetail extends RunSummary {
  params: RunParamsPayload;
  /** Server-derived Tier-D/Tier-K decision; clients cannot assert it. */
  reference_feasibility?: Record<string, unknown> | null;
  /** Server-derived objective request/admission receipt. */
  objective_fitness_receipt?: {
    requested_metric?: string | null;
    objective_requested?: boolean;
    blind_ablation_acknowledged?: boolean;
    dry_run?: boolean;
    effective_metric?: string | null;
    resolved_metric?: string | null;
    effective_mode?: "observe" | "steer" | null;
    blind_at_subprocess_start?: boolean;
    authorization?: string;
  } | null;
  /** Server-derived admission/worker pin for imported starting skills. */
  starting_skill_target_receipt?: {
    schema: number;
    adapter_class: string;
    task_id: string;
    robot_slug: string | null;
    policy_contract_required: boolean;
    policy_contract_sha256: string | null;
  } | null;
  iterations: IterEventSummary[];
  stdout_tail: string[];
  total_event_count: number;
}

/** One exportable trained iteration (GET /projects/{slug}/policies).
 *  Disk-backed — survives backend restarts, unlike RunSummary rows. */
export interface PolicySummary {
  iter_index: number;
  checkpoint: string; // "checkpoint.pt" | "checkpoint.zip"
  checkpoint_bytes: number;
  primary_metric: number | null;
  fitness: number | null;
  reward_version: string | null;
  metric_id: string | null;
  metric_version: string | null;
  metric_source: string | null;
  metric_sha256: string | null;
  criterion_status: "passed" | "failed" | "not_recorded";
  evidence_status: "complete" | "partial" | "unavailable";
  route_evidence: PolicyEvidenceValue | null;
  contact_evidence: PolicyEvidenceValue | null;
  hold_evidence: PolicyEvidenceValue | null;
  rollout_available: boolean;
  /** Earned only from a coherent immutable selection receipt. */
  selected: boolean;
  selection_source: string | null;
}

export interface PolicyEvidenceValue {
  key: string;
  value: number;
  kind: "fraction" | "count" | "frames" | "score" | "value";
}

// ── Starting skills (portable policy / motion import) ───────────────

export type StartingSkillInitializationMode =
  | "actor_only"
  | "actor_critic"
  | "reference_only"
  | "full_resume";

export type StartingSkillCompatibilityStatus =
  | "full_resume"
  | "transfer_actor_critic"
  | "transfer_actor"
  | "teacher_only"
  | "reference_only"
  | "partially_compatible"
  | "incompatible";

export interface StartingSkillRecord {
  skill_id: string;
  alias: string | null;
  created_at: string;
  adapter_class: string;
  task_id: string;
  robot_slug: string | null;
  source: string;
  checkpoint_sha256: string | null;
  checkpoint_size_bytes: number | null;
  /** Data format admitted by the server (for example `safetensors` or a
   * server-reserialized `sanitized_pt`). Optional for older library rows. */
  checkpoint_format?: string | null;
  source_format?: string | null;
  manifest_digest: string | null;
  identity_digest?: string | null;
  source_weights_sha256?: string | null;
  reference_clip_id: string | null;
  reference_robot: string | null;
  reference_sha256?: string | null;
  reference_provenance_sha256?: string | null;
  world_bundle_sha256?: string | null;
  controller_sha256?: string | null;
  compatibility_contract?: Record<string, unknown> | null;
  compatibility_contract_digest?: string | null;
  tensor_contract_verified?: boolean;
  tensor_signature_sha256?: string | null;
  initialization_modes: StartingSkillInitializationMode[];
  policy_roles: string[];
  trust_status: string;
}

export interface StartingSkillCompatibility {
  status: StartingSkillCompatibilityStatus;
  allowed_initialization_modes: StartingSkillInitializationMode[];
  reasons: string[];
  /** Stable machine-readable blockers paired with the researcher-facing
   * reason text. Older receipts may not include this field. */
  reason_codes?: string[];
  mode_reasons?: Partial<Record<StartingSkillInitializationMode, string[]>>;
  /** The sole admitted schema-2 -> schema-3 policy-interface extension.
   *  This is structural compatibility evidence, not launch authorization. */
  policy_contract_migration?: PolicyContractMigration | null;
}

export interface PolicyContractMigration {
  type: string;
  from_schema: number;
  to_schema: number;
  observation_term: string;
  extension_width: number;
  ordered_phase_ids: string[];
  optimizer_resume: false;
}

export interface StartingSkillTrustReceipt {
  status: "sanitized" | "verified_local" | string;
  detail?: string;
  source_format?: string | null;
  checkpoint_format?: string | null;
  manifest_digest: string | null;
  checkpoint_sha256: string | null;
  compatibility_contract_digest?: string | null;
  tensor_contract_verified?: boolean;
  tensor_signature_sha256?: string | null;
}

export interface StartingSkillComponents {
  policy_roles: string[];
  reference: {
    clip_id: string;
    robot: string;
    admission?: {
      status: "registered_candidate" | string;
      structural_checks: string[];
      training_authorized: boolean;
      next_gate: string;
    };
  } | null;
  world: {
    included: boolean;
    status: "digest_recorded_bytes_discarded" | "absent" | string;
    bytes_retained: boolean;
    activatable: boolean;
    sha256?: string | null;
  };
  controller: {
    kind: string;
    status: "digest_recorded_bytes_discarded" | string;
    bytes_retained: boolean;
    activatable: boolean;
    sha256?: string | null;
  } | null;
  excluded: string[];
}

/** Admission receipt returned both by list and import. It is intentionally
 * richer than the stored skill record so the UI can show researchers exactly
 * what will load, what was excluded, and why a bundle is incompatible. */
export interface StartingSkillReceipt {
  skill: StartingSkillRecord;
  /** Deprecated structural alias retained for older clients. It is not a
   * launch authorization; use `selectable` plus the run receipt. */
  compatible: boolean;
  selectable: boolean;
  training_authorized: false;
  /** Added by schema-v3 imports. Older disk receipts do not contain this
   * block, so clients must treat absence as blocked rather than crashing or
   * inferring launch authority. */
  authorization?: {
    status: "candidate" | "blocked" | string;
    receipt_scope: "structural_selectability_only" | string;
    training_authorized: false;
    mode_gates: Partial<Record<StartingSkillInitializationMode, string[]>>;
    detail: string;
    policy_present: boolean;
  };
  compatibility: StartingSkillCompatibility;
  trust: StartingSkillTrustReceipt;
  components: StartingSkillComponents;
  warnings: string[];
}

export interface StartingSkillsResponse {
  skills: StartingSkillReceipt[];
}

export interface StageReferenceAttachmentReceipt {
  stage: string;
  reference_clip_id: string;
  reference_tier: "D";
  reference_match_confidence: null;
  reference_robot: string;
  reference_clip_sha256: string;
  reference_certificate_sha256: string;
  reference_execution_contract_sha256: string;
  reference_execution_boundary_sha256: string;
}

export type StartingPointKind =
  | "scratch"
  | "project_checkpoint"
  | "shared_skill";

/** Controlled value emitted by StartingPointPickerDialog. Run fields retain
 * their API names; `kind` and `import_manifest_digest` are UI/provenance
 * context and must not be copied blindly into the POST body. */
export interface StartingPointSelection {
  kind: StartingPointKind;
  warm_start_iteration: number | null;
  starting_skill_id: string | null;
  initialization_mode: StartingSkillInitializationMode | null;
  reference_clip_id: string | null;
  reference_robot: string | null;
  import_manifest_digest: string | null;
  /** Copied from the selected import's compatibility receipt so the launch
   *  review can disclose it. Direct project checkpoints leave this null and
   *  are verified only by the launch path. */
  policy_contract_migration?: PolicyContractMigration | null;
}

/** Every event the WS stream emits. The frontend switches on
 *  `type` — other fields are payload extras. */
export interface RunEvent {
  type: string;
  seq: number;
  ts: string;
  /** Where the event came from. Set by the backend on every event. */
  origin?: "fs" | "stdout" | "user" | "cancel";
  /** Payload field, NOT provenance — emitters use it for real data (a warm
   *  start's checkpoint path, a selection's origin, a clip's dataset). It
   *  falls back to the origin only when the emitter left it unset, so read
   *  it as event-specific and validate before display. */
  source?: string;
  [extra: string]: unknown;
}

// ── Dashboard + System ──────────────────────────────────────────────
export interface DashboardRecentRun {
  run_id: string;
  project_slug: string;
  project_display_name: string;
  status: JobStatus;
  behavior_goal: string;
  iterations_completed: number;
  iterations_requested: number;
  primary_metric_history: Array<number | null>;
  started_at: string | null;
  ended_at: string | null;
}

export interface DashboardKGAddition {
  project_slug: string;
  project_display_name: string;
  arxiv_id: string;
  title: string;
  extracted: boolean;
  ingested_at: string | null;
}

export interface DashboardSummary {
  project_count: number;
  has_any_projects: boolean;
  active_jobs: JobSummary[];
  recent_runs: DashboardRecentRun[];
  recent_kg_additions: DashboardKGAddition[];
}

export interface SystemInfo {
  sculptor_ok: boolean;
  sculptor_error: string | null;
  projects_root: string;
  sculptor_path: string | null;
  anthropic_api_key_set: boolean;
  anthropic_api_key_masked: string | null;
  torch_available: boolean;
  cuda_available: boolean;
  cuda_device_count: number;
  cuda_device_names: string[];
}

export interface ApiKeyStatus {
  configured: boolean;
  masked: string | null;
  persisted: boolean;
}

// ── GPU info (GET /system/gpu) ─────────────────────────────────────────
export interface GpuDevice {
  index: number;
  name: string;
  total_memory_bytes: number;
  free_memory_bytes: number;
  used_memory_bytes?: number;
  utilization_percent?: number | null;
  temperature_c?: number | null;
  driver_version?: string | null;
  multi_processor_count: number;
  major: number;
  minor: number;
}

export interface SystemGpuResponse {
  torch_available: boolean;
  torch_version: string | null;
  cuda_available: boolean;
  cuda_version: string | null;
  cuda_version_ok: boolean;
  device_count: number;
  devices: GpuDevice[];
  mjlab_available: boolean;
  mujoco_warp_available: boolean;
  rsl_rl_available: boolean;
  pynvml_available?: boolean;
  import_error: string | null;
}

/** GET /system/kg/stats — aggregate counts over the shared user-wide KG
 * (M7 Phase 1). Returns zero-filled fields when `db_exists=false`. */
export interface SystemKgStatsResponse {
  db_path: string;
  db_exists: boolean;
  db_size_bytes: number;
  last_modified: string | null;
  papers: number;
  techniques: number;
  failure_modes: number;
  reward_components: number;
  environments: number;
  results: number;
  run_cases: number;
  edges: number;
  embeddings: number;
}

/** GET/PUT /system/remote — persisted remote-GPU dispatch settings
 * (§Ship 23d). Mirrors backend/services/remote_settings.RemoteSettings. */
export interface RemoteSettings {
  enabled: boolean;
  host: string;
  port: number;
  user: string;
  key_path: string;
  remote_workdir: string;
  remote_python: string;
  device: string;
  rollout_remote: boolean;
}

export interface RemoteDoctorCheck {
  name: string;
  ok: boolean;
  detail: string;
}

/** POST /system/remote/doctor — Test-connection report. */
export interface RemoteDoctorResponse {
  ok: boolean;
  host: string;
  port: number;
  checks: RemoteDoctorCheck[];
}

/** GET /projects/{slug}/rewards/{version}/diagnosis — shape of the
 * raw diagnosis.json payload written by sculptor.diagnose.
 * Fields are Optional on the TS side because older diagnoses may
 * be missing newer fields (schema has evolved since M0). */
export interface RewardDiagnosisPayload {
  failure_modes?: string[];
  evidence?: string;
  proposed_edits?: Array<{
    target_term: string;
    operation: string;
    rationale: string;
    suggested_value?: string | null;
    paper_refs?: string[];
    // Per-arxiv_id grounding for `paper_refs` above: true if the KG
    // actually showed that paper to the diagnoser this iteration,
    // false if it was cited from recall (exists in the KG, not
    // retrieved this iter). A key missing from this map (including on
    // diagnosis.json files predating the tag) means unknown, not false.
    paper_refs_grounded?: Record<string, boolean> | null;
    requires_env_extension?: boolean;
  }>;
  literature_context?: Array<{
    technique: string;
    description: string;
    paper_citation: string;
    relevance_score: number;
    // literature_context is, by construction, what the KG retrieved and
    // showed the diagnoser this iteration — true for current writers;
    // absent on diagnoses predating the tag.
    grounded?: boolean;
  }>;
  confidence?: number;
  iter_dir?: string | null;
  behavior_goal?: string | null;
}

/** Structured failure metadata (M7 Phase 6). Populated when a sculpt
 * subprocess exits non-zero and run_manager recognizes the failure
 * pattern (OOM, reward contract mismatch, CUDA mismatch, etc.). */
export interface ErrorClassification {
  kind:
    | "oom"
    | "reward_contract_mismatch"
    | "driver_version"
    | "no_cuda"
    | "unknown";
  title: string | null;
  detail: string | null;
  suggestions: string[];
  problem_type: string;
  action: {
    kind?: string;
    label?: string;
  } | null;
}

// ── Physics (M7 Phase 5) ────────────────────────────────────────────
export interface MjcfJointSummary {
  name: string;
  damping: number | null;
  armature: number | null;
  frictionloss: number | null;
  stiffness: number;
  range: [number, number] | null;
}

export interface MjcfActuatorSummary {
  name: string;
  forcerange: [number, number] | null;
  gear: number;
  gainprm: number[];
  biasprm: number[];
}

export interface MjcfGeomSummary {
  name: string;
  body_mass: number;
  friction: [number, number, number];
}

/** The rates training actually runs at. Distinct from `MjcfSummary.timestep`,
 *  which is only what the robot XML compiles to — for the G1 those differ by
 *  2.5x because mjlab's task config overrides the MJCF. */
export interface MjcfTiming {
  physics_dt: number;
  physics_hz: number;
  decimation: number;
  control_dt: number;
  control_hz: number;
  task_id: string;
  /** What the MJCF compiles to, for comparison. */
  mjcf_timestep: number | null;
  /** True when the task overrides the MJCF — the MJCF number is NOT the one
   *  that trains, and the panel says so. */
  mjcf_overridden: boolean;
  /** Advisory findings from `validate_timing` (Nyquist vs the reference,
   *  physics band, deployable control band, series elasticity). */
  findings: string[];
}

export interface MjcfSummary {
  timestep: number | null;
  gravity: number[] | null;
  integrator: string | null;
  solver: string | null;
  joint_defaults: Record<string, unknown>;
  joints: MjcfJointSummary[];
  actuators: MjcfActuatorSummary[];
  geoms: MjcfGeomSummary[];
  /** Populated when mujoco refuses the MJCF (missing meshes, malformed
   *  XML, etc.). UI surfaces this inline + offers a "Re-materialize"
   *  button that re-copies the library source + assets. */
  parse_error: string | null;
  /** null when the project's task can't be resolved — rendered as "unknown"
   *  rather than defaulted, so a guess never looks like a measurement. */
  timing: MjcfTiming | null;
}

export interface PhysicsLoadResponse {
  xml_source: string;
  mjcf_source_kind: "library" | "upload" | "none";
  mjcf_path: string | null;
  materialized: boolean;
  summary: MjcfSummary;
}

// ── Robot library (M3) ──────────────────────────────────────────────────
export type RobotCategory =
  | "Quadruped"
  | "Humanoid"
  | "Arm"
  | "Gripper_Hand"
  | "Mobile_Manipulator"
  | "Drone"
  | "Biomechanical"
  | "Other";

export const ROBOT_CATEGORIES: readonly RobotCategory[] = [
  "Quadruped",
  "Humanoid",
  "Arm",
  "Gripper_Hand",
  "Mobile_Manipulator",
  "Drone",
  "Biomechanical",
  "Other",
] as const;

/** Default category filter (M3 — Cartpole lives under "Other" and is
 *  opt-in via the filter chip). */
export const DEFAULT_CATEGORIES: readonly RobotCategory[] = [
  "Quadruped",
  "Humanoid",
  "Arm",
  "Gripper_Hand",
] as const;

export type TrainingSupport =
  | "mjlab_ready"
  | "preview_only"
  | "gymnasium_compatible";

export const DEFAULT_TRAINING_SUPPORT: readonly TrainingSupport[] = [
  "mjlab_ready",
  "gymnasium_compatible",
] as const;

export type LibrarySource = "menagerie" | "mjlab_builtin" | "gymnasium_builtin";

export interface LibraryReference {
  kind: "paper" | "repo";
  url: string;
  citation: string;
}

export interface LibraryPreconfiguredTask {
  task_id: string;
  display_name: string;
  recommended_num_envs: number;
}

export interface LibraryRobot {
  slug: string;
  reference_robot: string;
  display_name: string;
  category: RobotCategory;
  description: string;
  source: LibrarySource;
  menagerie_package: string | null;
  training_support: TrainingSupport;
  is_smoke_test_target: boolean;
  preconfigured_tasks: LibraryPreconfiguredTask[];
  references: LibraryReference[];
  thumbnail_path: string;
  demote_note?: string | null;
}

export interface LibraryListResponse {
  robots: LibraryRobot[];
  total: number;
  categories: string[];
}

// ── Adapter registry (M5) ───────────────────────────────────────────
export interface AdapterInfo {
  name: string;
  display_name: string;
  class_path: string;
  status: "ready" | "coming_soon";
  supported_robot_categories: string[];
  adoption_guide_url: string;
  estimated_effort: string;
}

// ── Missions (Ship 18a) ─────────────────────────────────────────────
// Mirrors backend/models/mission.py.

export type StageStatus =
  | "pending"
  | "training"
  | "succeeded"
  | "failed"
  | "skipped"
  // §mission-persistence: replaced by redecomposition children; terminal,
  // never runnable again, artifacts retained on disk.
  | "superseded";

export type MissionLifecycleStatus =
  | "ready"
  | "running"
  | "completed"
  | "halted"
  | "errored";

export type MissionJobKind = "mission_decompose" | "mission_execute";

export interface StageSchema {
  name: string;
  goal_text: string;
  success_criterion: string;
  max_iterations: number;
  parent_stage: string | null;
  reward_seed_prompt: string;
  kg_seed_papers: string[];

  status: StageStatus;
  final_policy_path: string | null;
  final_reward_path: string | null;
  best_metric: number | null;
  iterations_used: number;
  started_at: string | null;
  finished_at: string | null;
  redecomposition_attempts: number;
  // §Ship 20a: persisted cap actually enforced for the stage's last
  // (or current) run — `iterations_override or max_iterations`. Null
  // for stages that haven't run yet. Use this for `rounds X/Y`
  // display so it stays correct after the WS event window slides;
  // fall back to max_iterations only when null.
  effective_max_iterations: number | null;
  // §Ship 20 (de-siloing): the iteration the stage actually KEPT as its
  // policy, and why it was chosen. Both null until selection runs (a
  // stage can be `succeeded` with these still null on older missions).
  selected_iter_index?: number | null;
  selection_source?:
    | "criterion+fitness"
    | "criterion_newest"
    | "fitness_fallback"
    | "last"
    | string
    | null;
  // §mission-persistence: why the stage ended non-successfully
  // ("criterion_not_met", "training_errored", "no_checkpoint", ...).
  // Persisted on the stage going forward; enriched from provenance.json
  // for older missions. Null when the stage hasn't failed.
  failure_reason?: string | null;
  failure_detail?: string | null;
  // Per-stage objective metric ref (spec name / gen:<id> / path), if any.
  steering_metric?: string | null;
  // Server-computed hierarchical number: "1", "1.1", "1.2", "2", ... —
  // replan children get parentLabel.N. Use this instead of array index
  // or RunSummary.stage_index for user-facing numbering.
  display_label?: string;
  // True for stages reconstructed from an orphaned stages/<name>/ dir
  // on disk (pre-fix destructive replan) rather than mission.json.
  on_disk_only?: boolean;
  // How this stage got (or failed to get) its objective metric.
  metric_status?: "accepted" | "rejected" | "inherited" | "none" | null;
  // §D28 F-SYNTH: derived (not mirrored from sculptor.mission.Stage) —
  // "synthetic" when the accepted metric was certified against a
  // last-resort synthesized exemplar (no matching reference clip;
  // never steer-grade on its own — observe-grade until task-derived
  // calibration), "reference" when a real reference_clip_id is
  // attached with no synthetic exemplar, null otherwise.
  exemplar_kind?: "reference" | "synthetic" | null;
  // §R1 (reference library): attached reference clip, if any. Set via
  // POST/DELETE .../stages/{stage}/reference (see lib/api.ts). tier and
  // match_confidence are mirrored from the clip's provenance / the
  // retrieval result at attach time — null when nothing is attached, or
  // when attached without a confidence (deterministic-only match).
  reference_clip_id?: string | null;
  reference_tier?: string | null;
  reference_match_confidence?: number | null;
  // Immutable Tier-D admission receipt. Nullable only for legacy mission
  // reads; attached runnable stages are rejected unless artifact and
  // execution-boundary pins are all present.
  reference_robot?: string | null;
  reference_clip_sha256?: string | null;
  reference_certificate_sha256?: string | null;
  reference_execution_contract_sha256?: string | null;
  reference_execution_boundary_sha256?: string | null;
  // §D24 F1: the goal-aligned sub-span of reference_clip_id, when one
  // was selected (docs/internal/REFERENCE_BUILD_LOG.md D23/D24). All
  // four null together when no span applies (no clip attached, the
  // goal covers the whole clip, or selection was declined) — the stage
  // then certifies/trains against the FULL clip.
  reference_span_start_s?: number | null;
  reference_span_end_s?: number | null;
  reference_span_confidence?: number | null;
  reference_span_method?: string | null;
  // §start_pose: the physical configuration the robot is in at THIS
  // stage's episode start. null = unspecified (legacy missions, or a
  // decomposer that omitted the field — NOT the same as "standing").
  start_pose?:
    | "supine"
    | "prone"
    | "sitting"
    | "crouched"
    | "standing"
    | string
    | null;
}

// ── Stage iterations (disk-truth, de-siloed) ─────────────────────────
// GET /projects/{slug}/missions/{ms}/stages/{stage}/iterations → every
// iteration that landed on disk for that stage, independent of which
// stage the live UI is scoped to. Metrics are null until they land.
export interface StageIteration {
  iter_index: number;
  primary_metric: number | null;
  fitness: number | null;
  has_rollout: boolean;
  has_checkpoint: boolean;
  reward_version: string | null;
  // §D24 (F4): true when `<iter_dir>/fitness_contradiction.json` exists —
  // this iter's success criterion evaluated True while the objective
  // fitness was at/near zero (the D20 hollow-success / D23 exemplar-
  // scope-mismatch pattern). `fitness_components` is the per-channel
  // breakdown from that same flag file, for the badge's tooltip.
  fitness_contradiction: boolean;
  fitness_components: Record<string, number | boolean> | null;
  // §selection-report UI: the loop's OWN steering score for this iter —
  // `fitness` above is the plain objective fitness; `steer_fitness` is
  // what actually drove keep-best when a realism/naturalness gate could
  // veto credit (they diverge when the gate fired). `progress` is the
  // dense per-iter progress signal (not the same scale as fitness).
  steer_fitness: number | null;
  progress: number | null;
  // Naturalness/realism audit outcome for this iter, if the audit ran —
  // e.g. "reset_launch_explosion". null when the audit didn't flag
  // anything (or didn't run). `naturalness_hard_reject` is true when the
  // flag was severe enough to zero out steering credit outright.
  naturalness_flag: string | null;
  naturalness_hard_reject: boolean;
  // Where `fitness`/`steer_fitness` came from: "live" when the run wrote
  // it directly, "log_backfill" when a later backfill pass recovered it
  // from run logs after the fact, null when neither ran.
  fitness_source: "live" | "log_backfill" | null;
  /** Fresh held-out replay videos stored for selected-best evaluation. */
  fresh_rollout_count: number;
}

// GET .../stages/{stage}/selection — the stage's keep-best decision
// report, disk-truth. When `synthesized` is true, the report was
// reconstructed from mission.json (older stages that predate live
// selection.json writing) — `candidates[].criterion_pass` is always null
// in that case since only the live writer knows what the criterion
// evaluated to per-candidate at selection time. The backend model is
// deliberately loose (`extra=allow`), so treat unlisted keys as possible.
export interface StageSelectionCandidate {
  iter_index: number;
  criterion_pass: boolean | null;
  criterion_error: string | null;
  gate_mismatched: boolean;
  fitness: number | null;
  steer_fitness: number | null;
  progress: number | null;
  steer_progress: number | null;
  primary_metric: number | null;
  selected: boolean;
}

export interface StageSelectionReport {
  synthesized: boolean;
  schema: number;
  stage: string;
  recorded_at: string | null;
  selected_iter_index: number | null;
  selection_source: string | null;
  criterion_ok: boolean | null;
  criterion: string | null;
  criterion_error: string | null;
  start_state_mismatch: string | null;
  failure_reason?: string | null;
  failure_detail?: string | null;
  gate: { skipped: boolean; checked: number; mismatched_count: number } | null;
  candidates: StageSelectionCandidate[];
}

// POST .../missions/{mission_slug}/backfill-fitness → summary of a
// disk-log fitness recovery pass. `stages` maps stage name to the count
// of fitness.json files written for that stage this call — stages with
// nothing to backfill are absent, not zero-valued. 409s while a mission
// job is live.
export interface BackfillFitnessResponse {
  written: number;
  skipped_existing: number;
  no_iter_dir: number;
  stages: Record<string, number>;
}

// ── Completed-stage per-iteration detail (disk-truth) ────────────────
// GET .../stages/{stage}/iterations/{i}/detail → the reasoning behind a
// finished iteration (diagnosis, cited papers, reward summary, component
// values) so the Training tab's disk-truth pane is as rich as the live
// pane. All fields best-effort from the iter dir; any may be null.
export interface StageIterPaperRef {
  arxiv_id?: string | null;
  citation?: string | null;
  description?: string | null;
  // true: retrieved from the KG this iteration. false: cited by the
  // diagnoser from recall (exists in the KG but wasn't retrieved this
  // iter). null/undefined: unknown, or predates the grounding tag.
  grounded?: boolean | null;
}
export interface StageIterDetail {
  iter_index: number;
  reward_version: string | null;
  reward_description: string | null;
  reward_references: StageIterPaperRef[];
  primary_metric: number | null;
  // Objective (steering) fitness the loop optimized this iter, if the
  // metric wrote a structured value; otherwise null and the prose in
  // `evidence` states it.
  objective_fitness: number | null;
  evidence: string | null;
  confidence: number | null;
  failure_modes: string[];
  literature_context: StageIterPaperRef[];
  // Mean value per reward component over the rollout, if available.
  components: Record<string, number> | null;
}

// §R1 remainder (plan §9): one reference clip a stage's objective metric
// was certified against. Mirrors backend/models/mission.py's
// StageMetricReference — clip_id + the three per-reference gate verdicts
// (reference_nondegeneracy / reference_monotonicity / reference_negatives).
export interface StageMetricReference {
  clip_id: string;
  gates: Record<string, boolean>;
}

// GET .../stages/{stage}/metric → the stage's objective-metric record
// (what was generated, whether the adversarial panel accepted it).
export interface StageObjectiveMetric {
  status: "accepted" | "rejected" | "inherited" | "none";
  behavior_goal: string | null;
  metric_source: string | null;
  validation_passed: boolean | null;
  review_summary: string | null;
  n_candidates: number | null;
  calibrated: boolean | null;
  validator_basis: string | null;
  abstract_objective_program: string[];
  channel_catalog_hash: string | null;
  references: StageMetricReference[];
}

// GET .../stages/{stage}/env-spec → the stage's applied env curriculum.
// `current.meta.source` starting with "reference:" means RSI (reference-
// state-init) was applied for this stage.
export interface StageEnvSpecMeta {
  behavior_goal?: string | null;
  reasoning?: string | null;
  source?: string | null;
  version?: string | null;
  [key: string]: unknown;
}

export interface StageEnvSpecCurrent {
  env_spec_version?: number;
  meta?: StageEnvSpecMeta;
  shared?: Record<string, unknown>;
  train?: Record<string, unknown>;
  [key: string]: unknown;
}

export interface StageEnvSpec {
  active?: boolean;
  current?: StageEnvSpecCurrent | null;
  versions?: string[];
}

export interface MissionSummary {
  mission_slug: string;
  project_slug: string;
  goal: string;
  n_stages: number;
  current_stage_idx: number;
  decomposition_model: string;
  created_at: string;  // ISO-8601
  lifecycle: MissionLifecycleStatus;
  active_job_id: string | null;
  active_job_kind: MissionJobKind | null;
}

export interface MissionDetail extends MissionSummary {
  stages: StageSchema[];
  decomposition_rationale: string;
  schema_version: number;
  // §Ship 21a: persisted run-time defaults set up front via the
  // NewMissionDialog Advanced tab. RunMissionDialog pre-fills its
  // inputs from this on first open. Keys mirror RunMissionRequestBody.
  // Null when none were set at creation time.
  run_defaults?: MissionRunDefaults | null;
}

/** §Ship 21a: same shape as RunMissionRequestBody (api.ts) but lives
 *  in types.ts because it's the persisted view of the same payload. */
export interface MissionRunDefaults {
  iterations_override?: number | null;
  steps_per_iter?: number | null;
  seed?: number | null;
  early_stop_on_criterion?: boolean;
  criterion_stability_window?: number;
  extend_on_improvement?: boolean;
  max_extensions_per_stage?: number;
  extension_factor?: number;
  extension_improvement_threshold?: number;
  // §Ship 34/35: per-stage objective fitness-in-the-loop (built-in name
  // or "gen:<id>") + observe/steer mode.
  fitness_metric?: string | null;
  fitness_mode?: "observe" | "steer";
  // §MISSION_RUN_PARITY: per-launch knobs mirrored from NewRunDialog's
  // stage-applicable set. All optional; blank = the stage's inherited
  // config default. Applied uniformly to every stage.
  edit_candidates?: number | null;
  rollout_episodes?: number | null;
  max_episode_steps?: number | null;
  playback_speed?: number | null;
  render_width?: number | null;
  render_height?: number | null;
  fitness_patience?: number | null;
  num_envs_override?: number | null;
  device_override?: string | null;
}

export interface CreateMissionRequest {
  goal: string;             // 8-2000 chars
  mission_slug?: string;    // optional override
  no_kg?: boolean;
  // §MISSION_RUN_PARITY: per-stage trust-gated metric generation. Default
  // ON; best-of-N candidates sampled per stage (1..4).
  gen_stage_metrics?: boolean;
  stage_metric_candidates?: number;
  // §mission-persistence increment 2: when true, `POST .../run` 409s
  // while any runnable stage lacks a steering metric, unless the run
  // request sets `proceed_blind`. Persisted into `run_defaults` at
  // creation time by the backend. Default false.
  stage_metric_required?: boolean;
  // §Ship 21a: optional run-time defaults set via the NewMission
  // Dialog Advanced tab. Persisted on the mission so RunMissionDialog
  // can pre-fill on first open.
  run_defaults?: MissionRunDefaults | null;
}

export interface DeleteMissionResponse {
  mission_slug: string;
  freed_bytes: number;
}

/** WebSocket envelope for mission events. Per Ship 18a plan-review,
 *  events are validated server-side as `dict[str, Any]` (only `type`
 *  is structural); narrow on `type` per-event in the consumer. */
export interface MissionEvent {
  type: string;
  stage_name?: string | null;
  stage_index?: number | null;
  ts?: number | null;
  source?: "stdout" | string;
  // Per-event-type fields are open. Examples:
  //   mission_started: { goal, stage_count }
  //   stage_completed_training: { stage_name, iterations_run, ... }
  //   stage_redecomposed: { original_stage_name, sub_stage_names, ... }
  [key: string]: unknown;
}

// ── Saved missions (durable disk archive) ────────────────────────────
// GET /saved → slim manifests; GET /saved/{id} → full manifest +
// mission.json. Files (mp4 / md) are served from /saved/{id}/file/{relpath}.
export interface SavedKeptCheckpoint {
  iter: number;
  bytes: number;
  reason: string; // "best" | "final" | ...
}

/** Slim per-stage row in the /saved LIST projection. */
export interface SavedStageSlim {
  name: string;
  status: string;
  best_metric: number | null;
  n_kept_checkpoints: number;
}

export interface SavedEntrySummary {
  entry_id: string;
  project_slug: string;
  mission_slug: string;
  goal: string;
  created_at: string; // ISO-8601
  stages: SavedStageSlim[];
  total_bytes: number;
  /** Relpath under the entry, served via /saved/{id}/file/{relpath}.
   *  Often null. */
  thumbnail_video: string | null;
}

/** Fuller per-stage section in the /saved/{id} DETAIL manifest. */
export interface SavedStageDetail {
  name: string;
  status: string;
  best_metric: number | null;
  n_iters?: number;
  /** Relpaths (served via the file endpoint), newest-last. */
  videos: string[];
  kept_checkpoints: SavedKeptCheckpoint[];
}

export interface SavedEntryDetail {
  entry_id: string;
  project_slug: string;
  mission_slug: string;
  goal: string;
  created_at: string;
  schema: number;
  total_bytes: number;
  dropped_bytes?: number;
  source_mission_dir?: string;
  stages: SavedStageDetail[];
  // The archived mission.json (open shape; stages carry selection info).
  mission_json?: Record<string, unknown>;
}

// ── Reports (project-runs vs per-mission) ────────────────────────────
// GET /projects/{slug}/reports/sources → what can be built/viewed as a
// report. `project_runs` is the standalone-run report; each mission is
// its own buildable/viewable source.
export interface ReportMissionSource {
  mission_slug: string;
  goal: string;
  lifecycle: MissionLifecycleStatus;
  has_report: boolean;
}

export interface ReportsSources {
  project_runs: { n_iters: number; has_report: boolean };
  missions: ReportMissionSource[];
}

// ── Trash (recoverable deletes) ──────────────────────────────────────
// GET /trash → list of soft-deleted entries. A delete moves the entry
// into a trash dir; restore moves it back, purge removes it for good.
export interface TrashEntry {
  entry_id: string;
  kind: string;            // e.g. "project" | "mission" | "saved"
  slug: string;
  deleted_at: string;      // ISO-8601
  size_bytes: number;
  display_name: string;
  /** True when the on-disk entry couldn't be introspected (corrupt /
   *  partial). Restore is still allowed; the UI flags it. */
  unreadable?: boolean;
}

// ── Shared stage selection (de-silo, Ship 20+) ────────────────────────
// A stage selection shared across the Overview / Rewards / Training tabs
// on ProjectDetail, URL-synced as `?stage=missionSlug/stageName`. Lives
// here (not in pages/ProjectDetail) so components like RobotViewer and
// RunsTab can import the type without a circular import back into the
// page module.
export interface SelectedStage {
  missionSlug: string;
  stageName: string;
}

// ── Reference library (R1) ───────────────────────────────────────────
// GET /references?robot=&q=&k=&llm= — a retrieval search hit. Mirrors
// sculptor's RefMatch dataclass (refs/retrieve.py) 1:1.
export interface RefMatch {
  clip_id: string;
  text: string;
  score: number;
  /** 0-1 confidence from the optional LLM rerank pass; null when the
   *  search ran deterministic-only (llm=0, the UI's as-you-type default,
   *  or the LLM rerank failed and fell back). */
  match_confidence: number | null;
  /** One-line LLM rationale; null on the deterministic-only path. */
  reason: string | null;
  tier: string;
  license: string;
  n_frames: number;
  fps: number;
  duration_s: number;
}

// GET /references (no q) — slim index row. Also the shape of the
// GET /references/{clip_id} detail's `index` field.
export interface RefIndexRow {
  clip_id: string;
  robot: string;
  text: string;
  labels: string[];
  tier: string;
  license: string;
  n_frames: number;
  fps: number;
  duration_s: number;
  root_z_range: [number, number] | null;
  has_preview: boolean;
}

// POST /references/compose — one span of one already-registered clip.
export interface ComposeSegment {
  clip_id: string;
  t_start_s?: number | null;
  t_end_s?: number | null;
  label?: string | null;
}

// Per-seam discontinuity measured on the composed clip. This is the number
// that decides whether a composite is worth a tracking run, so it is shown
// rather than reduced to a pass/fail badge.
export interface ComposeSeam {
  frame: number;
  time_s: number;
  max_joint_jump_rad?: number;
  mean_joint_jump_rad?: number;
  root_z_jump_m?: number;
}

export interface ComposeQc {
  n_frames: number;
  duration_s: number;
  n_sources: number;
  root_z_range: [number, number] | null;
  composition: {
    seams: ComposeSeam[];
    peak_joint_vel_rad_s: number | null;
    peak_root_vel_z_m_s: number | null;
    duration_s: number;
  };
}

export interface ComposeResult {
  clip_id: string;
  robot: string;
  tier: string;
  /** Always false on creation — refs.track certification is the only
   *  thing that promotes a composite past kinematics. */
  certified: boolean;
  license: string;
  attribution: string;
  parent_clip_ids: string[];
  qc: ComposeQc;
  next_step: string;
}

// GET /references/{clip_id} — provenance.json content + the index row.
export interface RefDetail {
  index_row: RefIndexRow;
  provenance: Record<string, unknown> | null;
  dynamics_admission: {
    admitted: boolean;
    tier: string;
    certificate_digest: string | null;
    clip_sha256: string | null;
    rollout_sha256: string | null;
    reason: string | null;
    tracking_errors?: {
      mean_joint_err_rad: number;
      max_joint_err_rad: number;
      root_z_rmse_m: number;
    };
  };
}

// ── Worlds (environment authoring, item 5) ─────────────────────────────
export interface WorldClarificationChoice {
  choice_id: string;
  label: string;
  [extra: string]: unknown;
}

export interface WorldSystemDefault {
  choice_id: "system_default";
  resolves_to: string;
  label: string;
  reason: string;
}

export interface WorldClarificationQuestion {
  question_id: string;
  parameter_path: string;
  prompt: string;
  choices: WorldClarificationChoice[];
  default_choice_id: string;
  default_reason: string;
  system_default: WorldSystemDefault;
}

export interface WorldClarificationPage {
  page: number;
  questions: WorldClarificationQuestion[];
}

export interface WorldClarificationPlan {
  version: number;
  draft_hash: string;
  question_set_hash: string;
  pages: WorldClarificationPage[];
}

export interface WorldAuthorRequest {
  prompt: string;
  robot_capability_id?: string | null;
  kg_grounding?: boolean;
}

export interface WorldAuthorResponse {
  session_id: string;
  draft_hash: string;
  capability_id: string;
  /** The project's configured robot as a capability id (null when no
   *  capability descriptor maps to it) + whether the draft matches it. */
  project_capability_id: string | null;
  robot_matches_project: boolean | null;
  clarification_plan: WorldClarificationPlan;
  underspecification_report: {
    defaulted_load_bearing_paths: string[];
    [extra: string]: unknown;
  };
  kg_grounding: string[];
}

export interface WorldApplyRequest {
  session_id: string;
  answers: { question_id: string; choice_id: string }[];
}

export interface WorldApplyResponse {
  ok: boolean;
  session_id: string;
  capability_id: string;
  result_hash: string;
  evaluation_lineage: string;
  selection: { selection_version: number; tuple_hash: string;
    [extra: string]: unknown };
  admission: { ok: boolean; [extra: string]: unknown };
  clarification_answers: number;
  [extra: string]: unknown;
}

export interface WorldSelection {
  selection: { selection_version: number; tuple_hash: string;
    evaluation_lineage: string;
    refs?: Record<string, {
      kind: string; version: string; path: string; sha256: string;
    }>;
    [extra: string]: unknown };
  world_meta: { version?: string; parent?: string | null; prompt?: string;
    grounding?: string[]; [extra: string]: unknown };
  task_meta: { [extra: string]: unknown };
  shared_summary: {
    terrain_kind: string | null;
    objects: string[];
    zones: string[];
    course_elements: number;
    /** Per-element-type counts (e.g. {platform: 3, gap: 2}) — gaps are
     *  spacing elements with no geometry, so the total can exceed what
     *  the rendered scene shows as solids. */
    course_breakdown: Record<string, number>;
    robot: string | null;
    project_capability_id: string | null;
    robot_matches_project: boolean | null;
  };
  goal: { [extra: string]: unknown };
  train_variations: {
    id: string; target: string; class: string;
    distribution: { [extra: string]: unknown };
  }[];
  clarifications: {
    answer_sources: Record<string, number>;
    answers: {
      question_id: string | null;
      parameter_path: string | null;
      choice_id: string | null;
      source: string | null;
      value: unknown;
    }[];
  };
  /** Present only for an admitted TaskSpec with shared.event_sequence. */
  event_program?: WorldEventProgram;
}

export interface WorldEventProgramTransition {
  from: string;
  to: string;
  when: Record<string, unknown>;
}

export interface WorldEventProgram {
  id: string;
  ordered_phase_ids: ["route", "jump", "hold"];
  transition_spec: WorldEventProgramTransition[];
  minimum_air_time_s: number;
  minimum_height_delta_m: number;
  support_selectors: [string, string][];
  terminal_hold_duration_s: number;
  episode_length_s: number;
  train_only_phase_sampling: Record<string, number>;
  evaluation_start_phase: "route";
  observation_extension: {
    term: "authored_event_phase";
    encoding: "one_hot";
    width: 3;
  };
  provenance: {
    selection_version: number;
    selection_tuple_hash: string;
    task_artifact: {
      kind: string; version: string; path: string; sha256: string;
    };
  };
}

export interface WorldLineageEntry {
  selection_version: number;
  created_at: number;
  tuple_hash: string;
  evaluation_lineage: string;
  refs: Record<string, { version: string | number | null }>;
  eval_model_hash: string | null;
}

export interface WorldValidateResult {
  ok: boolean;
  selection_version: number | null;
  tuple_hash: string | null;
  errors: string[];
}

export interface WorldCurriculumIteration {
  iter: number;
  mean_level: number | null;
  max_level: number | null;
  num_envs: number | null;
  histogram: Record<string, number> | null;
}

export interface WorldCurriculum {
  run: string | null;
  iterations: WorldCurriculumIteration[];
}

// ── World scene graph (interactive 3D viewer) ──────────────────────────
export interface WorldSceneGeom {
  name: string;
  body: string;
  type: string; // plane | hfield | sphere | capsule | ellipsoid | cylinder | box | mesh
  size: number[];
  pos: number[];
  quat: number[]; // [w, x, y, z]
  rgba: number[];
  group: number;
  entity_kind: string; // course_element | robot | terrain | object | zone
  entity_id: string;
  mesh?: string;
  hfield?: string;
}

export interface WorldSceneSite {
  name: string;
  type: string;
  size: number[];
  pos: number[];
  quat: number[];
  rgba: number[];
  entity_kind: string;
  entity_id: string;
}

export interface WorldSceneEntity {
  kind: string;
  id: string;
  label: string;
  element?: string;
  params: Record<string, unknown>;
  variations: {
    id: string; target: string; class: string;
    distribution: Record<string, unknown>;
  }[];
  geoms: string[];
  sites?: string[];
  /** Synthetic translucent box for geometry-less elements (gaps). */
  marker?: { pos: number[]; size: number[] };
}

export interface WorldScene {
  selection_version?: number;
  tuple_hash?: string;
  meshes: Record<string, { vertices: number[]; faces: number[] }>;
  hfields: Record<string, {
    nrow: number; ncol: number; size: number[]; data: number[];
  }>;
  geoms: WorldSceneGeom[];
  sites: WorldSceneSite[];
  entities: WorldSceneEntity[];
}

export interface WorldVariationEditResult {
  applied: {
    variation_id: string;
    old_distribution: Record<string, unknown>;
    new_distribution: Record<string, unknown>;
    rationale: string;
  }[];
  rejected: { variation_id: string; reason: string }[];
  selection: { selection_version: number;
    [extra: string]: unknown } | null;
  world_version: string | null;
}

export interface WorldDraftPreview {
  ok: boolean;
  session_id: string;
  result_hash: string;
  admission: {
    ok: boolean;
    gates: {
      gate: string; ok: boolean;
      violations: { code: string; message: string;
        [extra: string]: unknown }[];
    }[];
  };
  scene: WorldScene | null;
  summary: {
    robot: string | null;
    terrain_kind: string | null;
    course_elements: number;
    course_breakdown: Record<string, number>;
    objects: string[];
    zones: string[];
  };
}
