/** Types mirroring `backend/models/*.py` Pydantic schemas.
 *  Kept in sync by hand until Prompt 10 wires openapi-typescript. */

export type ProjectStatus =
  | "draft"
  | "configured"
  | "ready"
  | "running"
  | "completed"
  | "errored";

export interface ProjectSummary {
  slug: string;
  display_name: string;
  description: string;
  status: ProjectStatus;
  created_at: string;
  env_id: string | null;
  n_iterations_completed: number;
  // M6: populated when the project references an adapter no longer in
  // ADAPTER_REGISTRY. UI shows a banner hinting at "fork to upgrade".
  migration_warning?: string | null;
  // §Ship 22b (re-skin, Finding A): additive card enrichment from
  // GET /projects. Config fields filled by ProjectStore.list(); metric
  // fields filled by the route from the latest sculpt_run.
  adapter_class?: string | null;
  library_slug?: string | null;
  num_envs?: number | null;
  device?: string | null;
  primary_metric?: number | null;
  primary_metric_history?: Array<number | null>;
}

export interface ProjectDetail extends ProjectSummary {
  project_dir: string;
  adapter_class: string;
  adapter_config: Record<string, unknown>;
  ready_to_train?: boolean;
  library_slug?: string | null;
  adapter_unavailable?: boolean;
}

export interface HealthResponse {
  status: "ok" | "degraded";
  sculptor_ok: boolean;
  sculptor_error: string | null;
  projects_root: string;
}

export interface CreateProjectPayload {
  name: string; // maps to display_name server-side
  description?: string;
  adapter?: string;
  iteration_budget?: number;
  behavior_goal?: string;
  // M3 / M4 additions. Backend derives adapter + task_id from
  // library_slug when present; explicit num_envs / gpu_device override
  // the library entry's defaults.
  library_slug?: string;
  task_id?: string;
  num_envs?: number;
  gpu_device?: string;
}

export type RobotKind = "library" | "mjcf" | "urdf" | "none";

export interface RobotStateResponse {
  kind: RobotKind;
  library_name: string | null;
  env_id: string | null;
  model_file: string | null;
  original_filename: string | null;
  size_bytes: number | null;
  uploaded_at: string | null;
  mesh_paths: string[];
}

export type LibraryRobotName =
  | "hopper"
  | "half_cheetah"
  | "ant"
  | "humanoid"
  | "walker2d";

export type CameraAngle = "iso" | "front" | "side" | "top";
export const CAMERA_ANGLES: readonly CameraAngle[] = [
  "iso",
  "front",
  "side",
  "top",
] as const;

/** Wire-format + thumbnail path + display label for each library
 *  robot. Thumbnail lives under frontend/public/robots/ and is
 *  regenerated by scripts/generate_library_thumbnails.py. */
export interface LibraryRobotEntry {
  name: LibraryRobotName;
  displayName: string;
  envId: string;
  thumbnail: string;
  blurb: string;
}

export const LIBRARY_ROBOTS: readonly LibraryRobotEntry[] = [
  {
    name: "hopper",
    displayName: "Hopper",
    envId: "Hopper-v4",
    thumbnail: "/robots/hopper.png",
    blurb: "2D single-leg hopper — canonical locomotion testbed.",
  },
  {
    name: "half_cheetah",
    displayName: "Half-Cheetah",
    envId: "HalfCheetah-v4",
    thumbnail: "/robots/half_cheetah.png",
    blurb: "Planar bipedal runner with a low-slung torso.",
  },
  {
    name: "walker2d",
    displayName: "Walker2D",
    envId: "Walker2d-v4",
    thumbnail: "/robots/walker2d.png",
    blurb: "2D bipedal walker — upright gait, fall-prone without shaping.",
  },
  {
    name: "ant",
    displayName: "Ant",
    envId: "Ant-v4",
    thumbnail: "/robots/ant.png",
    blurb: "Quadruped ant body — omnidirectional locomotion.",
  },
  {
    name: "humanoid",
    displayName: "Humanoid",
    envId: "Humanoid-v4",
    thumbnail: "/robots/humanoid.png",
    blurb: "Full-body humanoid — high-DOF, reward-shaping hard mode.",
  },
] as const;

export interface ProblemDetail {
  type: string;
  title: string;
  status: number;
  detail: string | null;
  instance?: string | null;
  [extra: string]: unknown;
}

// ── Rewards ─────────────────────────────────────────────────────────
export type RewardAuthor = "sculptor" | "human" | "unknown";

export interface RewardRef {
  arxiv_id: string;
  citation: string;
}

export interface RewardSpec {
  version: string;
  parent_hash: string;
  author: string;
  description: string;
  hyperparameters: Record<string, number>;
  references: RewardRef[];
  /** Map of `hparam_name → citation-or-justification` — the KG-grounding
   *  mandate from 2026-04-22. Empty for pre-mandate rewards.
   *  SpecPanel renders this alongside hyperparameters so Sam can audit
   *  which arxiv_id / physics principle justifies each numeric choice. */
  grounding: Record<string, string>;
}

export interface ComponentProbe {
  ok: boolean;
  components: Record<string, number> | null;
  total: number | null;
  error: string | null;
}

export interface RewardVersionSummary {
  version: number;
  file_name: string;
  author: RewardAuthor;
  parent_hash: string;
  parent_version: number | null;
  description: string;
  iter_introduced: number | null;
  n_references: number;
  primary_metric: number | null;
  metric_delta: number | null;
  created_at: string;
}

export interface RewardVersionDetail extends RewardVersionSummary {
  source: string;
  spec: RewardSpec;
  components_probe: ComponentProbe;
}

export interface ManualEditPayload {
  source: string;
  expected_parent_version: number;
  note?: string;
}

// ── KG ──────────────────────────────────────────────────────────────
export interface PaperSummary {
  id: string;
  arxiv_id: string;
  title: string;
  authors: string[];
  year: number | null;
  extracted: boolean;
  has_pdf: boolean;
}

export type KGEntityKind =
  | "Technique"
  | "FailureMode"
  | "RewardComponent"
  | "Environment";

export interface KGEntitySummary {
  id: string;
  kind: KGEntityKind;
  name: string;
  description: string;
}

export interface PaperEntities {
  techniques: KGEntitySummary[];
  failure_modes: KGEntitySummary[];
  reward_components: KGEntitySummary[];
  environments: KGEntitySummary[];
}

export interface PaperDetail extends PaperSummary {
  abstract: string;
  conclusion_text: string;
  pdf_available: boolean;
  ingested_at: string | null;
  entities: PaperEntities;
}

export interface TechniqueSummary {
  id: string;
  name: string;
  description: string;
  tags: string[];
  n_addresses: number;
  introduced_by: string[];
}

export interface PendingSeed {
  arxiv_id: string;
  title?: string;
  rationale?: string;
}

export interface PendingSeedsResponse {
  pending: PendingSeed[];
  ingested_count: number;
}

export interface KGStats {
  papers: number;
  techniques: number;
  failure_modes: number;
  reward_components: number;
  environments: number;
  results: number;
  edges: number;
  embeddings: number;
}

export interface AddSeedsPayload {
  seeds: Array<{ arxiv_id: string; title?: string; rationale?: string }>;
  auto_extract?: boolean;
}

// ── Jobs ────────────────────────────────────────────────────────────
export type JobKind =
  | "kg_ingest"
  | "kg_extract"
  | "kg_ingest_extract"
  | "kg_research"
  | "kg_viz_render"
  | "sculpt_run";

export type JobStatus =
  | "queued"
  | "running"
  | "completed"
  | "errored"
  | "stopped";

export const JOB_TERMINAL_STATES: readonly JobStatus[] = [
  "completed",
  "errored",
  "stopped",
] as const;

export interface JobSummary {
  job_id: string;
  kind: JobKind;
  project_slug: string | null;
  status: JobStatus;
  progress: number | null;
  message: string | null;
  started_at: string | null;
  ended_at: string | null;
  error: string | null;
}

export interface JobDetail extends JobSummary {
  params: Record<string, unknown>;
  result: Record<string, unknown> | null;
}

// ── Runs ────────────────────────────────────────────────────────────
export interface RunParamsPayload {
  behavior_goal: string;
  iterations: number;
  no_kg?: boolean;
  dry_run?: boolean;
  // M7 Phase 4 — GPU-appropriate overrides. All optional; null means
  // "use the project's config.toml default".
  training_iterations?: number | null;
  num_envs_override?: number | null;
  device_override?: string | null;
  expand_kg?: boolean;
  // Ship-7 — rollout video + RL knobs. All optional; null means runner
  // default (real-time 500-step video, 6 episodes, seed from config).
  max_episode_steps?: number | null;
  playback_speed?: number | null;
  render_every?: number | null;
  rollout_fps?: number | null;
  rollout_episodes?: number | null;
  seed?: number | null;
  auto_adjust_physics?: boolean | null;
  // Legacy compatibility no-ops; metric-plateau auto-kill is disabled.
  early_stop_enabled?: boolean | null;
  early_stop_patience?: number | null;
  // §Ship 34/35 — objective fitness-in-the-loop. A built-in spec name
  // (go1_trot / g1_kick / g1_floss / cartpole_balance) or a generated
  // metric id ("gen:<id>"); null = the blind loop.
  fitness_metric?: string | null;
  // observe = compute + display only (no influence); steer = drives the loop.
  fitness_mode?: "observe" | "steer";
  // §Ship 39 (H1): interactive start mode. "manual" pauses for human feedback
  // at each iteration boundary (the UI default); "auto" runs straight through.
  start_mode?: "manual" | "auto";
}

/** §Ship 39 (H1): the interactive control sidecar state (PATCH response). */
export interface RunControlState {
  mode: string;
  resume_token: number;
  feedback?: string | null;
  stop: boolean;
}

/** §Ship 34: spec metrics selectable as in-loop objective fitness.
 *  Mirrors sculptor.eval.spec_metrics._SPEC_FNS / the backend Literal. */
export type SpecMetricName =
  | "cartpole_balance"
  | "g1_floss"
  | "g1_kick"
  | "go1_trot";

/** §Ship 35: an auto-generated objective metric (per project), referenced
 *  in a run as fitness_metric = "gen:<id>". Observe-only until calibrated. */
export interface MetricSummary {
  id: string;
  behavior_goal?: string | null;
  accepted: boolean;
  validation_passed: boolean;
  calibrated: boolean;
  review?: { approved?: boolean; concerns?: string[]; summary?: string } | null;
  gates?: Record<string, boolean> | null;
  reasons?: string[] | null;
  archetype_scores?: Record<string, number> | null;
  calibration?: { ok?: boolean; spearman?: number; builtin?: string } | null;
  source?: string | null;
  recorded_at?: string | null;
}

export const SPEC_METRIC_NAMES: SpecMetricName[] = [
  "cartpole_balance",
  "g1_floss",
  "g1_kick",
  "go1_trot",
];

// Extend RunSummary / RunDetail with the new Phase-6 classification
// field. Existing callers that spread `...run` keep working.
export interface RunErrorClassificationFields {
  error_classification?: ErrorClassification | null;
}

export interface RealismAuditPayload {
  verdict: "ok" | "mild" | "severe" | "unknown" | string;
  torque_saturation_frac?: number | null;
  any_joint_saturation_max?: number | null;
  joint_vel_p99_max?: number | null;
  joint_vel_multiplier_vs_nominal?: number | null;
  joint_limit_violation_frac?: number | null;
  top_joints_saturation?: Array<{ name: string; value: number }>;
  top_joints_vel?: Array<{ name: string; value: number }>;
  top_joints_limit_violation?: Array<{ name: string; value: number }>;
  n_actuators?: number;
  n_joints?: number;
  n_steps?: number;
  reason?: string;
}

export interface PhysicsEditSuggestionPayload {
  prompt: string;
  verdict?: string | null;
  top_joints_saturation?: Array<{ name: string; value: number }>;
  // §Ship-8c: sculpt-side auto-apply progress. UI disables the
  // "apply physics fix" chip while this is "in_progress" so a user
  // click can't race against the sculpt loop's own apply.
  auto_apply_state?:
    | "pending"
    | "in_progress"
    | "applied"
    | "rejected"
    | "errored"
    | "skipped";
  auto_apply_summary?: string;
  auto_apply_reason?: string;
}

export interface IterEventSummary {
  iter_index: number;
  status: "running" | "completed" | "errored" | "stopped";
  started_at: string | null;
  completed_at: string | null;
  reward_version_before: number | null;
  reward_version_after: number | null;
  primary_metric: number | null;
  metric_delta: number | null;
  failure_modes: string[];
  edit_count: number | null;
  paper_refs: string[];
  rollout_ready: boolean;
  diagnosed: boolean;
  // §7.3: post-rollout physics realism audit. `null` when
  // `realism_audit.json` hasn't landed on disk yet (iter still running,
  // or pre-§7.3 iter). Verdict + metric fields match
  // `sculptor.adapters.realism.audit_rollout()`.
  realism_audit: RealismAuditPayload | null;
  // §7.4: ready-to-apply MJCF-edit prompt when audit verdict is
  // "severe" AND project config has `auto_adjust_physics = true`. UI
  // surfaces as a chip that opens the Physics tab with prompt pre-filled.
  physics_edit_suggestion: PhysicsEditSuggestionPayload | null;
  // Populated by `iter_progress` events emitted from inside the mjlab
  // training subprocess. Lets the Timeline panel render a live progress
  // bar for the running iter instead of a silent "running" spinner.
  rl_iter?: number;
  rl_total?: number;
  pct?: number;
  elapsed_s?: number;
  eta_s?: number | null;
  // §Ship 34: objective fitness-in-the-loop. `fitness` is this iter's
  // ground-truth spec score; `best_fitness` is the best so far (the
  // version best-by-fitness selection keeps). Both undefined for blind
  // runs (no --fitness-metric).
  fitness?: number | null;
  best_fitness?: number | null;
}

export interface RunSummary {
  run_id: string;
  project_slug: string;
  status: JobStatus;
  behavior_goal: string;
  iterations_requested: number;
  iterations_completed: number;
  current_iter_index: number | null;
  // §Ship 35: per-iter objective fitness (parallel to primary_metric_history).
  // Empty/all-null for blind runs. When present, the UI foregrounds this as
  // the primary metric and demotes the reward metric to secondary.
  fitness_history?: Array<number | null>;
  primary_metric_history: Array<number | null>;
  started_at: string | null;
  ended_at: string | null;
  error: string | null;
  error_classification?: ErrorClassification | null;
  // §Ship 21: distinguish standalone sculpt_run rows from per-stage
  // mission_stage_run rows. The Runs sidebar groups stage runs under
  // their parent mission. Backend defaults to "sculpt_run" for
  // backward compatibility, so undefined === "sculpt_run".
  kind?: "sculpt_run" | "mission_stage_run";
  parent_id?: string | null;
  mission_slug?: string | null;
  stage_name?: string | null;
  stage_index?: number | null;
  // §Ship 39 (H1): current interactive mode ("manual" | "auto"); null for
  // older / non-interactive runs. Restores the Auto/Manual toggle on reconnect.
  mode?: string | null;
}

export interface RunDetail extends RunSummary {
  params: RunParamsPayload;
  iterations: IterEventSummary[];
  stdout_tail: string[];
  total_event_count: number;
}

/** Every event the WS stream emits. The frontend switches on
 *  `type` — other fields are payload extras. */
export interface RunEvent {
  type: string;
  seq: number;
  ts: string;
  source?: "fs" | "stdout" | "user" | "cancel";
  [extra: string]: unknown;
}

// ── Dashboard + System ──────────────────────────────────────────────
export interface DashboardRecentRun {
  run_id: string;
  project_slug: string;
  project_display_name: string;
  status: JobStatus;
  behavior_goal: string;
  iterations_completed: number;
  iterations_requested: number;
  primary_metric_history: Array<number | null>;
  started_at: string | null;
  ended_at: string | null;
}

export interface DashboardKGAddition {
  project_slug: string;
  project_display_name: string;
  arxiv_id: string;
  title: string;
  extracted: boolean;
  ingested_at: string | null;
}

export interface DashboardSummary {
  project_count: number;
  has_any_projects: boolean;
  active_jobs: JobSummary[];
  recent_runs: DashboardRecentRun[];
  recent_kg_additions: DashboardKGAddition[];
}

export interface SystemInfo {
  sculptor_ok: boolean;
  sculptor_error: string | null;
  projects_root: string;
  sculptor_path: string | null;
  anthropic_api_key_set: boolean;
  anthropic_api_key_masked: string | null;
  torch_available: boolean;
  cuda_available: boolean;
  cuda_device_count: number;
  cuda_device_names: string[];
}

// ── GPU info (GET /system/gpu) ─────────────────────────────────────────
export interface GpuDevice {
  index: number;
  name: string;
  total_memory_bytes: number;
  free_memory_bytes: number;
  used_memory_bytes?: number;
  utilization_percent?: number | null;
  temperature_c?: number | null;
  driver_version?: string | null;
  multi_processor_count: number;
  major: number;
  minor: number;
}

export interface SystemGpuResponse {
  torch_available: boolean;
  torch_version: string | null;
  cuda_available: boolean;
  cuda_version: string | null;
  cuda_version_ok: boolean;
  device_count: number;
  devices: GpuDevice[];
  mjlab_available: boolean;
  mujoco_warp_available: boolean;
  rsl_rl_available: boolean;
  pynvml_available?: boolean;
  import_error: string | null;
}

/** GET /system/kg/stats — aggregate counts over the shared user-wide KG
 * (M7 Phase 1). Returns zero-filled fields when `db_exists=false`. */
export interface SystemKgStatsResponse {
  db_path: string;
  db_exists: boolean;
  db_size_bytes: number;
  last_modified: string | null;
  papers: number;
  techniques: number;
  failure_modes: number;
  reward_components: number;
  environments: number;
  results: number;
  edges: number;
  embeddings: number;
}

/** GET/PUT /system/remote — persisted remote-GPU dispatch settings
 * (§Ship 23d). Mirrors backend/services/remote_settings.RemoteSettings. */
export interface RemoteSettings {
  enabled: boolean;
  host: string;
  port: number;
  user: string;
  key_path: string;
  remote_workdir: string;
  remote_python: string;
  device: string;
  rollout_remote: boolean;
}

export interface RemoteDoctorCheck {
  name: string;
  ok: boolean;
  detail: string;
}

/** POST /system/remote/doctor — Test-connection report. */
export interface RemoteDoctorResponse {
  ok: boolean;
  host: string;
  port: number;
  checks: RemoteDoctorCheck[];
}

/** GET /projects/{slug}/rewards/{version}/diagnosis — shape of the
 * raw diagnosis.json payload written by sculptor.diagnose.
 * Fields are Optional on the TS side because older diagnoses may
 * be missing newer fields (schema has evolved since M0). */
export interface RewardDiagnosisPayload {
  failure_modes?: string[];
  evidence?: string;
  proposed_edits?: Array<{
    target_term: string;
    operation: string;
    rationale: string;
    suggested_value?: string | null;
    paper_refs?: string[];
    requires_env_extension?: boolean;
  }>;
  literature_context?: Array<{
    technique: string;
    description: string;
    paper_citation: string;
    relevance_score: number;
  }>;
  confidence?: number;
  iter_dir?: string | null;
  behavior_goal?: string | null;
}

/** Structured failure metadata (M7 Phase 6). Populated when a sculpt
 * subprocess exits non-zero and run_manager recognizes the failure
 * pattern (OOM, reward contract mismatch, CUDA mismatch, etc.). */
export interface ErrorClassification {
  kind:
    | "oom"
    | "reward_contract_mismatch"
    | "driver_version"
    | "no_cuda"
    | "unknown";
  title: string | null;
  detail: string | null;
  suggestions: string[];
  problem_type: string;
  action: {
    kind?: string;
    label?: string;
  } | null;
}

// ── Physics (M7 Phase 5) ────────────────────────────────────────────
export interface MjcfJointSummary {
  name: string;
  damping: number | null;
  armature: number | null;
  frictionloss: number | null;
  stiffness: number;
  range: [number, number] | null;
}

export interface MjcfActuatorSummary {
  name: string;
  forcerange: [number, number] | null;
  gear: number;
  gainprm: number[];
  biasprm: number[];
}

export interface MjcfGeomSummary {
  name: string;
  body_mass: number;
  friction: [number, number, number];
}

export interface MjcfSummary {
  timestep: number | null;
  gravity: number[] | null;
  integrator: string | null;
  solver: string | null;
  joint_defaults: Record<string, unknown>;
  joints: MjcfJointSummary[];
  actuators: MjcfActuatorSummary[];
  geoms: MjcfGeomSummary[];
  /** Populated when mujoco refuses the MJCF (missing meshes, malformed
   *  XML, etc.). UI surfaces this inline + offers a "Re-materialize"
   *  button that re-copies the library source + assets. */
  parse_error: string | null;
}

export interface PhysicsLoadResponse {
  xml_source: string;
  mjcf_source_kind: "library" | "upload" | "none";
  mjcf_path: string | null;
  materialized: boolean;
  summary: MjcfSummary;
}

// ── Robot library (M3) ──────────────────────────────────────────────────
export type RobotCategory =
  | "Quadruped"
  | "Humanoid"
  | "Arm"
  | "Gripper_Hand"
  | "Mobile_Manipulator"
  | "Drone"
  | "Biomechanical"
  | "Other";

export const ROBOT_CATEGORIES: readonly RobotCategory[] = [
  "Quadruped",
  "Humanoid",
  "Arm",
  "Gripper_Hand",
  "Mobile_Manipulator",
  "Drone",
  "Biomechanical",
  "Other",
] as const;

/** Default category filter (M3 — Cartpole lives under "Other" and is
 *  opt-in via the filter chip). */
export const DEFAULT_CATEGORIES: readonly RobotCategory[] = [
  "Quadruped",
  "Humanoid",
  "Arm",
  "Gripper_Hand",
] as const;

export type TrainingSupport =
  | "mjlab_ready"
  | "preview_only"
  | "gymnasium_compatible";

export const DEFAULT_TRAINING_SUPPORT: readonly TrainingSupport[] = [
  "mjlab_ready",
  "gymnasium_compatible",
] as const;

export type LibrarySource = "menagerie" | "mjlab_builtin" | "gymnasium_builtin";

export interface LibraryReference {
  kind: "paper" | "repo";
  url: string;
  citation: string;
}

export interface LibraryPreconfiguredTask {
  task_id: string;
  display_name: string;
  recommended_num_envs: number;
}

export interface LibraryRobot {
  slug: string;
  display_name: string;
  category: RobotCategory;
  description: string;
  source: LibrarySource;
  menagerie_package: string | null;
  training_support: TrainingSupport;
  is_smoke_test_target: boolean;
  preconfigured_tasks: LibraryPreconfiguredTask[];
  references: LibraryReference[];
  thumbnail_path: string;
  demote_note?: string | null;
}

export interface LibraryListResponse {
  robots: LibraryRobot[];
  total: number;
  categories: string[];
}

// ── Adapter registry (M5) ───────────────────────────────────────────
export interface AdapterInfo {
  name: string;
  display_name: string;
  class_path: string;
  status: "ready" | "coming_soon";
  supported_robot_categories: string[];
  adoption_guide_url: string;
  estimated_effort: string;
}

// ── Missions (Ship 18a) ─────────────────────────────────────────────
// Mirrors backend/models/mission.py.

export type StageStatus =
  | "pending"
  | "training"
  | "succeeded"
  | "failed"
  | "skipped";

export type MissionLifecycleStatus =
  | "ready"
  | "running"
  | "completed"
  | "halted"
  | "errored";

export type MissionJobKind = "mission_decompose" | "mission_execute";

export interface StageSchema {
  name: string;
  goal_text: string;
  success_criterion: string;
  max_iterations: number;
  parent_stage: string | null;
  reward_seed_prompt: string;
  kg_seed_papers: string[];

  status: StageStatus;
  final_policy_path: string | null;
  final_reward_path: string | null;
  best_metric: number | null;
  iterations_used: number;
  started_at: string | null;
  finished_at: string | null;
  redecomposition_attempts: number;
  // §Ship 20a: persisted cap actually enforced for the stage's last
  // (or current) run — `iterations_override or max_iterations`. Null
  // for stages that haven't run yet. Use this for `rounds X/Y`
  // display so it stays correct after the WS event window slides;
  // fall back to max_iterations only when null.
  effective_max_iterations: number | null;
}

export interface MissionSummary {
  mission_slug: string;
  project_slug: string;
  goal: string;
  n_stages: number;
  current_stage_idx: number;
  decomposition_model: string;
  created_at: string;  // ISO-8601
  lifecycle: MissionLifecycleStatus;
  active_job_id: string | null;
  active_job_kind: MissionJobKind | null;
}

export interface MissionDetail extends MissionSummary {
  stages: StageSchema[];
  decomposition_rationale: string;
  schema_version: number;
  // §Ship 21a: persisted run-time defaults set up front via the
  // NewMissionDialog Advanced tab. RunMissionDialog pre-fills its
  // inputs from this on first open. Keys mirror RunMissionRequestBody.
  // Null when none were set at creation time.
  run_defaults?: MissionRunDefaults | null;
}

/** §Ship 21a: same shape as RunMissionRequestBody (api.ts) but lives
 *  in types.ts because it's the persisted view of the same payload. */
export interface MissionRunDefaults {
  iterations_override?: number | null;
  steps_per_iter?: number | null;
  seed?: number | null;
  early_stop_on_criterion?: boolean;
  criterion_stability_window?: number;
  extend_on_improvement?: boolean;
  max_extensions_per_stage?: number;
  extension_factor?: number;
  extension_improvement_threshold?: number;
  // §Ship 34/35: per-stage objective fitness-in-the-loop (built-in name
  // or "gen:<id>") + observe/steer mode.
  fitness_metric?: string | null;
  fitness_mode?: "observe" | "steer";
}

export interface CreateMissionRequest {
  goal: string;             // 8-2000 chars
  mission_slug?: string;    // optional override
  no_kg?: boolean;
  // §Ship 21a: optional run-time defaults set via the NewMission
  // Dialog Advanced tab. Persisted on the mission so RunMissionDialog
  // can pre-fill on first open.
  run_defaults?: MissionRunDefaults | null;
}

export interface DeleteMissionResponse {
  mission_slug: string;
  freed_bytes: number;
}

/** WebSocket envelope for mission events. Per Ship 18a plan-review,
 *  events are validated server-side as `dict[str, Any]` (only `type`
 *  is structural); narrow on `type` per-event in the consumer. */
export interface MissionEvent {
  type: string;
  stage_name?: string | null;
  stage_index?: number | null;
  ts?: number | null;
  source?: "stdout" | string;
  // Per-event-type fields are open. Examples:
  //   mission_started: { goal, stage_count }
  //   stage_completed_training: { stage_name, iterations_run, ... }
  //   stage_redecomposed: { original_stage_name, sub_stage_names, ... }
  [key: string]: unknown;
}
