"""v0 — starter reward generated by `sculpt init`. Replace with your domain.

Signature contract:

    compute_reward(state, action, next_state, info)
        -> (reward: float, components: dict[str, float])
"""

from __future__ import annotations


REWARD_SPEC: dict = {
    "version": "v0",
    "parent_hash": "",
    "description": (
        "Starter reward. Returns a constant alive_bonus so the adapter's "
        "preflight validator passes. Edit this file (or let `sculpt run` "
        "edit it) to encode your target behavior."
    ),
    "author": "human",
    "hyperparameters": {
        "alive_bonus": 1.0,
    },
    "references": [],
}


def compute_reward(state, action, next_state, info):
    alive = float(REWARD_SPEC["hyperparameters"]["alive_bonus"])
    components = {"alive_bonus": alive}
    return alive, components
