"""Auto-generated by sculptor.edit. Re-exports the latest reward.

Latest: v3.py
"""

import importlib.util
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_LATEST = _HERE / 'v3.py'

_spec = importlib.util.spec_from_file_location(
    "sculptor_reward_latest", str(_LATEST))
if _spec is None or _spec.loader is None:
    raise ImportError(f"could not load latest reward from {_LATEST}")
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)

compute_reward = _mod.compute_reward
REWARD_SPEC = _mod.REWARD_SPEC

__all__ = ["compute_reward", "REWARD_SPEC"]
